// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

package publisher

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	stdpath "path"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/microsoft/terraform-provider-power-platform/internal/api"
	"github.com/microsoft/terraform-provider-power-platform/internal/customerrors"
	"github.com/microsoft/terraform-provider-power-platform/internal/helpers"
)

var _ resource.Resource = &Resource{}
var _ resource.ResourceWithConfigure = &Resource{}
var _ resource.ResourceWithImportState = &Resource{}

var canonicalGuidRegex = regexp.MustCompile(helpers.GuidRegex)

func NewPublisherResource() resource.Resource {
	return &Resource{
		TypeInfo: helpers.TypeInfo{
			TypeName: "publisher",
		},
	}
}

func (r *Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	r.ProviderTypeName = req.ProviderTypeName

	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	resp.TypeName = r.FullTypeName()
	tflog.Debug(ctx, fmt.Sprintf("METADATA: %s", resp.TypeName))
}

func (r *Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Dataverse publisher record. Publishers own solution customization prefixes and related metadata.",
		Attributes: map[string]schema.Attribute{
			"timeouts": timeouts.Attributes(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"id": schema.StringAttribute{
				MarkdownDescription: "Dataverse publisher id.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"environment_id": schema.StringAttribute{
				MarkdownDescription: "Id of the Dataverse-enabled environment containing the publisher.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"uniquename": schema.StringAttribute{
				MarkdownDescription: "Unique name of the publisher.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"friendly_name": schema.StringAttribute{
				MarkdownDescription: "Display name of the publisher.",
				Required:            true,
			},
			"customization_prefix": schema.StringAttribute{
				MarkdownDescription: "Customization prefix used for solution components created by this publisher.",
				Required:            true,
			},
			"customization_option_value_prefix": schema.Int64Attribute{
				MarkdownDescription: "Option value prefix used for option set values created by this publisher. When omitted, the provider derives the same default value generated by the Power Apps publisher UI from `customization_prefix`.",
				Optional:            true,
				Computed:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description of the publisher.",
				Optional:            true,
			},
			"email_address": schema.StringAttribute{
				MarkdownDescription: "Email address for the publisher.",
				Optional:            true,
			},
			"supporting_website_url": schema.StringAttribute{
				MarkdownDescription: "Supporting website URL for the publisher.",
				Optional:            true,
			},
			"is_read_only": schema.BoolAttribute{
				MarkdownDescription: "Whether Dataverse reports this publisher as read only.",
				Computed:            true,
			},
			"address": schema.ListNestedAttribute{
				MarkdownDescription: "Up to two publisher addresses, mapped to Dataverse address slots 1 and 2.",
				Optional:            true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.List{
					listvalidator.SizeAtMost(2),
				},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"slot": schema.Int64Attribute{
							MarkdownDescription: "Address slot number in Dataverse. Valid values are `1` and `2`.",
							Required:            true,
							Validators: []validator.Int64{
								int64validator.OneOf(1, 2),
							},
						},
						"address_id": schema.StringAttribute{
							MarkdownDescription: "Dataverse address identifier for the slot.",
							Computed:            true,
						},
						"address_type_code": schema.Int64Attribute{
							MarkdownDescription: "Address type code.",
							Optional:            true,
						},
						"city": schema.StringAttribute{
							MarkdownDescription: "City name.",
							Optional:            true,
						},
						"country": schema.StringAttribute{
							MarkdownDescription: "Country or region name.",
							Optional:            true,
						},
						"county": schema.StringAttribute{
							MarkdownDescription: "County name.",
							Optional:            true,
						},
						"fax": schema.StringAttribute{
							MarkdownDescription: "Fax number.",
							Optional:            true,
						},
						"latitude": schema.Float64Attribute{
							MarkdownDescription: "Latitude value.",
							Optional:            true,
						},
						"line1": schema.StringAttribute{
							MarkdownDescription: "Street line 1.",
							Optional:            true,
						},
						"line2": schema.StringAttribute{
							MarkdownDescription: "Street line 2.",
							Optional:            true,
						},
						"line3": schema.StringAttribute{
							MarkdownDescription: "Street line 3.",
							Optional:            true,
						},
						"longitude": schema.Float64Attribute{
							MarkdownDescription: "Longitude value.",
							Optional:            true,
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Address name.",
							Optional:            true,
						},
						"postal_code": schema.StringAttribute{
							MarkdownDescription: "Postal code.",
							Optional:            true,
						},
						"post_office_box": schema.StringAttribute{
							MarkdownDescription: "Post office box.",
							Optional:            true,
						},
						"shipping_method_code": schema.Int64Attribute{
							MarkdownDescription: "Shipping method code.",
							Optional:            true,
						},
						"state_or_province": schema.StringAttribute{
							MarkdownDescription: "State or province name.",
							Optional:            true,
						},
						"telephone1": schema.StringAttribute{
							MarkdownDescription: "Primary telephone number.",
							Optional:            true,
						},
						"telephone2": schema.StringAttribute{
							MarkdownDescription: "Secondary telephone number.",
							Optional:            true,
						},
						"telephone3": schema.StringAttribute{
							MarkdownDescription: "Tertiary telephone number.",
							Optional:            true,
						},
						"ups_zone": schema.StringAttribute{
							MarkdownDescription: "UPS zone value.",
							Optional:            true,
						},
						"utc_offset": schema.Int64Attribute{
							MarkdownDescription: "UTC offset for the address.",
							Optional:            true,
						},
					},
				},
			},
		},
	}
}

func (r *Resource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	if req.ProviderData == nil {
		return
	}

	providerClient, ok := req.ProviderData.(*api.ProviderClient)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected ProviderData Type",
			fmt.Sprintf("Expected *api.ProviderClient, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.PublisherClient = newPublisherClient(providerClient.Api)
}

func (r *Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	var plan ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateAddressSlots(plan.Address)...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisher, err := r.PublisherClient.CreatePublisher(ctx, plan.EnvironmentId.ValueString(), &plan)
	if err != nil {
		if isPublisherAlreadyExistsError(err) {
			existing, lookupErr := r.PublisherClient.GetPublisherByUniqueName(ctx, plan.EnvironmentId.ValueString(), plan.UniqueName.ValueString())
			if lookupErr == nil && existing != nil {
				resp.Diagnostics.AddError(
					"Publisher already exists",
					fmt.Sprintf(
						"A Dataverse publisher with unique name `%s` already exists in environment `%s`. Import it using `terraform import <resource-address> %s` or choose a different `uniquename`.",
						plan.UniqueName.ValueString(),
						plan.EnvironmentId.ValueString(),
						buildPublisherImportId(plan.EnvironmentId.ValueString(), existing.Id),
					),
				)
				return
			}

			resp.Diagnostics.AddError(
				"Publisher already exists",
				fmt.Sprintf(
					"A Dataverse publisher with unique name `%s` already exists in environment `%s`. Import the existing publisher into state or choose a different `uniquename`.",
					plan.UniqueName.ValueString(),
					plan.EnvironmentId.ValueString(),
				),
			)
			return
		}

		resp.Diagnostics.AddError(fmt.Sprintf("Client error when creating %s", r.FullTypeName()), err.Error())
		return
	}

	setResourceModelFromDto(&plan, plan.EnvironmentId.ValueString(), publisher)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	var state ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisher, err := r.PublisherClient.GetPublisherById(ctx, state.EnvironmentId.ValueString(), state.Id.ValueString())
	if err != nil {
		if errors.Is(err, customerrors.ErrObjectNotFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(fmt.Sprintf("Client error when reading %s", r.FullTypeName()), err.Error())
		return
	}

	setResourceModelFromDto(&state, state.EnvironmentId.ValueString(), publisher)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	var plan ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)

	var state ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(validateAddressSlots(plan.Address)...)
	if resp.Diagnostics.HasError() {
		return
	}

	publisher, err := r.PublisherClient.UpdatePublisher(ctx, state.EnvironmentId.ValueString(), state.Id.ValueString(), &plan)
	if err != nil {
		resp.Diagnostics.AddError(fmt.Sprintf("Client error when updating %s", r.FullTypeName()), err.Error())
		return
	}

	setResourceModelFromDto(&plan, state.EnvironmentId.ValueString(), publisher)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	var state ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	if state.Id.IsNull() || state.EnvironmentId.IsNull() {
		return
	}

	err := r.PublisherClient.DeletePublisher(ctx, state.EnvironmentId.ValueString(), state.Id.ValueString())
	if err != nil && !errors.Is(err, customerrors.ErrObjectNotFound) {
		resp.Diagnostics.AddError(fmt.Sprintf("Client error when deleting %s", r.FullTypeName()), err.Error())
	}
}

func (r *Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	ctx, exitContext := helpers.EnterRequestContext(ctx, r.TypeInfo, req)
	defer exitContext()

	parts := strings.SplitN(req.ID, "_", 2)
	if len(parts) != 2 || !isGuid(parts[0]) || !isGuid(parts[1]) {
		resp.Diagnostics.AddError(
			"Invalid import ID",
			fmt.Sprintf("Expected import ID in format 'environment_id_publisher_id', got '%s'", req.ID),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("environment_id"), parts[0])...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), parts[1])...)
}

func validateAddressSlots(addresses []PublisherAddressModel) (diags diag.Diagnostics) {
	seen := map[int64]struct{}{}
	for idx, address := range addresses {
		if address.Slot.IsNull() || address.Slot.IsUnknown() {
			diags.AddAttributeError(
				path.Root("address").AtListIndex(idx).AtName("slot"),
				"Missing address slot",
				"Each address entry must declare a slot value of 1 or 2.",
			)
			continue
		}

		slot := address.Slot.ValueInt64()
		if _, exists := seen[slot]; exists {
			diags.AddAttributeError(
				path.Root("address").AtListIndex(idx).AtName("slot"),
				"Duplicate address slot",
				fmt.Sprintf("Only one address entry may target slot %d.", slot),
			)
			continue
		}
		seen[slot] = struct{}{}
	}
	return diags
}

func setResourceModelFromDto(model *ResourceModel, environmentId string, publisher *publisherDto) {
	existingAddresses := model.Address
	existingDescription := model.Description
	existingEmailAddress := model.EmailAddress
	existingSupportingWebsiteURL := model.SupportingWebsiteURL

	model.Id = types.StringValue(publisher.Id)
	model.EnvironmentId = types.StringValue(environmentId)
	model.UniqueName = types.StringValue(publisher.UniqueName)
	model.FriendlyName = types.StringValue(publisher.FriendlyName)
	model.CustomizationPrefix = types.StringValue(publisher.CustomizationPrefix)
	model.CustomizationOptionValuePrefix = types.Int64Value(publisher.CustomizationOptionValuePrefix)
	model.Description = normalizeNullableConfigString(publisher.Description, existingDescription)
	model.EmailAddress = normalizeNullableConfigString(publisher.EmailAddress, existingEmailAddress)
	model.SupportingWebsiteURL = normalizeNullableConfigString(publisher.SupportingWebsiteURL, existingSupportingWebsiteURL)
	model.IsReadOnly = types.BoolValue(publisher.IsReadOnly)
	model.Address = addressModelsFromDto(publisher, existingAddresses)
}

func publisherBodyFromModel(model *ResourceModel) map[string]any {
	body := map[string]any{
		"uniquename":                     model.UniqueName.ValueString(),
		"friendlyname":                   model.FriendlyName.ValueString(),
		"customizationprefix":            model.CustomizationPrefix.ValueString(),
		"customizationoptionvalueprefix": effectiveCustomizationOptionValuePrefix(model),
		"description":                    nullableStringPointer(model.Description),
		"emailaddress":                   nullableStringPointer(model.EmailAddress),
		"supportingwebsiteurl":           nullableStringPointer(model.SupportingWebsiteURL),
	}

	addressBySlot := map[int64]PublisherAddressModel{}
	for _, address := range model.Address {
		if address.Slot.IsNull() || address.Slot.IsUnknown() {
			continue
		}
		addressBySlot[address.Slot.ValueInt64()] = address
	}

	for _, slot := range []int64{1, 2} {
		address := addressBySlot[slot]
		prefix := fmt.Sprintf("address%d_", slot)
		body[prefix+"addresstypecode"] = nullableInt64Pointer(address.AddressTypeCode)
		body[prefix+"city"] = nullableStringPointer(address.City)
		body[prefix+"country"] = nullableStringPointer(address.Country)
		body[prefix+"county"] = nullableStringPointer(address.County)
		body[prefix+"fax"] = nullableStringPointer(address.Fax)
		body[prefix+"latitude"] = nullableFloat64Pointer(address.Latitude)
		body[prefix+"line1"] = nullableStringPointer(address.Line1)
		body[prefix+"line2"] = nullableStringPointer(address.Line2)
		body[prefix+"line3"] = nullableStringPointer(address.Line3)
		body[prefix+"longitude"] = nullableFloat64Pointer(address.Longitude)
		body[prefix+"name"] = nullableStringPointer(address.Name)
		body[prefix+"postalcode"] = nullableStringPointer(address.PostalCode)
		body[prefix+"postofficebox"] = nullableStringPointer(address.PostOfficeBox)
		body[prefix+"shippingmethodcode"] = nullableInt64Pointer(address.ShippingMethodCode)
		body[prefix+"stateorprovince"] = nullableStringPointer(address.StateOrProvince)
		body[prefix+"telephone1"] = nullableStringPointer(address.Telephone1)
		body[prefix+"telephone2"] = nullableStringPointer(address.Telephone2)
		body[prefix+"telephone3"] = nullableStringPointer(address.Telephone3)
		body[prefix+"upszone"] = nullableStringPointer(address.UpsZone)
		body[prefix+"utcoffset"] = nullableInt64Pointer(address.UtcOffset)
	}

	return body
}

func addressModelsFromDto(publisher *publisherDto, existing []PublisherAddressModel) []PublisherAddressModel {
	var addresses []PublisherAddressModel

	if address1 := addressModelFromDtoWithExisting(1, publisher, findAddressBySlot(existing, 1)); address1 != nil {
		if !isPlaceholderAddressModel(*address1) || hasAddressSlot(existing, 1) {
			addresses = append(addresses, *address1)
		}
	}
	if address2 := addressModelFromDtoWithExisting(2, publisher, findAddressBySlot(existing, 2)); address2 != nil {
		if !isPlaceholderAddressModel(*address2) || hasAddressSlot(existing, 2) {
			addresses = append(addresses, *address2)
		}
	}

	if len(addresses) == 0 {
		if existing != nil {
			return []PublisherAddressModel{}
		}
		return nil
	}

	return addresses
}

func addressModelFromDto(slot int64, publisher *publisherDto) *PublisherAddressModel {
	if publisher == nil {
		return nil
	}

	model := PublisherAddressModel{
		Slot: types.Int64Value(slot),
	}

	switch slot {
	case 1:
		model.AddressId = nullableStringValue(publisher.Address1AddressId)
		model.AddressTypeCode = nullableInt64Value(publisher.Address1AddressTypeCode)
		model.City = nullableStringValue(publisher.Address1City)
		model.Country = nullableStringValue(publisher.Address1Country)
		model.County = nullableStringValue(publisher.Address1County)
		model.Fax = nullableStringValue(publisher.Address1Fax)
		model.Latitude = nullableFloat64Value(publisher.Address1Latitude)
		model.Line1 = nullableStringValue(publisher.Address1Line1)
		model.Line2 = nullableStringValue(publisher.Address1Line2)
		model.Line3 = nullableStringValue(publisher.Address1Line3)
		model.Longitude = nullableFloat64Value(publisher.Address1Longitude)
		model.Name = nullableStringValue(publisher.Address1Name)
		model.PostalCode = nullableStringValue(publisher.Address1PostalCode)
		model.PostOfficeBox = nullableStringValue(publisher.Address1PostOfficeBox)
		model.ShippingMethodCode = nullableInt64Value(publisher.Address1ShippingMethodCode)
		model.StateOrProvince = nullableStringValue(publisher.Address1StateOrProvince)
		model.Telephone1 = nullableStringValue(publisher.Address1Telephone1)
		model.Telephone2 = nullableStringValue(publisher.Address1Telephone2)
		model.Telephone3 = nullableStringValue(publisher.Address1Telephone3)
		model.UpsZone = nullableStringValue(publisher.Address1UpsZone)
		model.UtcOffset = nullableInt64Value(publisher.Address1UtcOffset)
	case 2:
		model.AddressId = nullableStringValue(publisher.Address2AddressId)
		model.AddressTypeCode = nullableInt64Value(publisher.Address2AddressTypeCode)
		model.City = nullableStringValue(publisher.Address2City)
		model.Country = nullableStringValue(publisher.Address2Country)
		model.County = nullableStringValue(publisher.Address2County)
		model.Fax = nullableStringValue(publisher.Address2Fax)
		model.Latitude = nullableFloat64Value(publisher.Address2Latitude)
		model.Line1 = nullableStringValue(publisher.Address2Line1)
		model.Line2 = nullableStringValue(publisher.Address2Line2)
		model.Line3 = nullableStringValue(publisher.Address2Line3)
		model.Longitude = nullableFloat64Value(publisher.Address2Longitude)
		model.Name = nullableStringValue(publisher.Address2Name)
		model.PostalCode = nullableStringValue(publisher.Address2PostalCode)
		model.PostOfficeBox = nullableStringValue(publisher.Address2PostOfficeBox)
		model.ShippingMethodCode = nullableInt64Value(publisher.Address2ShippingMethodCode)
		model.StateOrProvince = nullableStringValue(publisher.Address2StateOrProvince)
		model.Telephone1 = nullableStringValue(publisher.Address2Telephone1)
		model.Telephone2 = nullableStringValue(publisher.Address2Telephone2)
		model.Telephone3 = nullableStringValue(publisher.Address2Telephone3)
		model.UpsZone = nullableStringValue(publisher.Address2UpsZone)
		model.UtcOffset = nullableInt64Value(publisher.Address2UtcOffset)
	}

	if model.AddressId.IsNull() &&
		model.AddressTypeCode.IsNull() &&
		model.City.IsNull() &&
		model.Country.IsNull() &&
		model.County.IsNull() &&
		model.Fax.IsNull() &&
		model.Latitude.IsNull() &&
		model.Line1.IsNull() &&
		model.Line2.IsNull() &&
		model.Line3.IsNull() &&
		model.Longitude.IsNull() &&
		model.Name.IsNull() &&
		model.PostalCode.IsNull() &&
		model.PostOfficeBox.IsNull() &&
		model.ShippingMethodCode.IsNull() &&
		model.StateOrProvince.IsNull() &&
		model.Telephone1.IsNull() &&
		model.Telephone2.IsNull() &&
		model.Telephone3.IsNull() &&
		model.UpsZone.IsNull() &&
		model.UtcOffset.IsNull() {
		return nil
	}

	if isAddressContentEmpty(model) && model.AddressTypeCode.IsNull() && model.ShippingMethodCode.IsNull() {
		return nil
	}

	return &model
}

func addressModelFromDtoWithExisting(slot int64, publisher *publisherDto, existing *PublisherAddressModel) *PublisherAddressModel {
	model := addressModelFromDto(slot, publisher)
	if model == nil || existing == nil {
		return model
	}

	model.City = normalizeNullableConfigStringValue(model.City, existing.City)
	model.Country = normalizeNullableConfigStringValue(model.Country, existing.Country)
	model.County = normalizeNullableConfigStringValue(model.County, existing.County)
	model.Fax = normalizeNullableConfigStringValue(model.Fax, existing.Fax)
	model.Line1 = normalizeNullableConfigStringValue(model.Line1, existing.Line1)
	model.Line2 = normalizeNullableConfigStringValue(model.Line2, existing.Line2)
	model.Line3 = normalizeNullableConfigStringValue(model.Line3, existing.Line3)
	model.Name = normalizeNullableConfigStringValue(model.Name, existing.Name)
	model.PostalCode = normalizeNullableConfigStringValue(model.PostalCode, existing.PostalCode)
	model.PostOfficeBox = normalizeNullableConfigStringValue(model.PostOfficeBox, existing.PostOfficeBox)
	model.StateOrProvince = normalizeNullableConfigStringValue(model.StateOrProvince, existing.StateOrProvince)
	model.Telephone1 = normalizeNullableConfigStringValue(model.Telephone1, existing.Telephone1)
	model.Telephone2 = normalizeNullableConfigStringValue(model.Telephone2, existing.Telephone2)
	model.Telephone3 = normalizeNullableConfigStringValue(model.Telephone3, existing.Telephone3)
	model.UpsZone = normalizeNullableConfigStringValue(model.UpsZone, existing.UpsZone)

	return model
}

func hasAddressSlot(addresses []PublisherAddressModel, slot int64) bool {
	for _, address := range addresses {
		if address.Slot.IsNull() || address.Slot.IsUnknown() {
			continue
		}
		if address.Slot.ValueInt64() == slot {
			return true
		}
	}
	return false
}

func findAddressBySlot(addresses []PublisherAddressModel, slot int64) *PublisherAddressModel {
	for idx := range addresses {
		if addresses[idx].Slot.IsNull() || addresses[idx].Slot.IsUnknown() {
			continue
		}
		if addresses[idx].Slot.ValueInt64() == slot {
			return &addresses[idx]
		}
	}
	return nil
}

func isPlaceholderAddressModel(model PublisherAddressModel) bool {
	if !isAddressContentEmpty(model) {
		return false
	}

	return isDefaultOrNullInt64(model.AddressTypeCode, 1) &&
		isDefaultOrNullInt64(model.ShippingMethodCode, 1)
}

func isAddressContentEmpty(model PublisherAddressModel) bool {
	return model.City.IsNull() &&
		model.Country.IsNull() &&
		model.County.IsNull() &&
		model.Fax.IsNull() &&
		model.Latitude.IsNull() &&
		model.Line1.IsNull() &&
		model.Line2.IsNull() &&
		model.Line3.IsNull() &&
		model.Longitude.IsNull() &&
		model.Name.IsNull() &&
		model.PostalCode.IsNull() &&
		model.PostOfficeBox.IsNull() &&
		model.StateOrProvince.IsNull() &&
		model.Telephone1.IsNull() &&
		model.Telephone2.IsNull() &&
		model.Telephone3.IsNull() &&
		model.UpsZone.IsNull() &&
		model.UtcOffset.IsNull()
}

func isDefaultOrNullInt64(value types.Int64, defaultValue int64) bool {
	return value.IsNull() || (!value.IsUnknown() && value.ValueInt64() == defaultValue)
}

func buildPublisherImportId(environmentId, publisherId string) string {
	return fmt.Sprintf("%s_%s", environmentId, publisherId)
}

func getPublisherIdFromResponse(resp *api.Response) (string, error) {
	var entityId string
	for headerName, values := range resp.HttpResponse.Header {
		if strings.EqualFold(headerName, "OData-EntityId") && len(values) > 0 {
			entityId = values[0]
			break
		}
	}
	if entityId == "" {
		return "", errors.New("no publisher id returned from the API")
	}

	parsed, err := url.Parse(entityId)
	if err != nil {
		return "", err
	}

	entitySegment := stdpath.Base(parsed.Path)
	publisherId, found := strings.CutPrefix(entitySegment, "publishers(")
	if !found {
		return "", errors.New("no publisher id returned from the API")
	}

	publisherId = strings.TrimSuffix(publisherId, ")")
	if !canonicalGuidRegex.MatchString(publisherId) {
		return "", errors.New("no publisher id returned from the API")
	}

	return publisherId, nil
}

func nullableStringValue(value string) types.String {
	if value == "" {
		return types.StringNull()
	}
	return types.StringValue(value)
}

func normalizeNullableConfigString(value string, existing types.String) types.String {
	if value != "" {
		return types.StringValue(value)
	}

	if !existing.IsNull() && !existing.IsUnknown() && existing.ValueString() == "" {
		return types.StringValue("")
	}

	return types.StringNull()
}

func normalizeNullableConfigStringValue(value types.String, existing types.String) types.String {
	if !value.IsNull() {
		return value
	}

	if !existing.IsNull() && !existing.IsUnknown() && existing.ValueString() == "" {
		return types.StringValue("")
	}

	return types.StringNull()
}

func effectiveCustomizationOptionValuePrefix(model *ResourceModel) int64 {
	if !model.CustomizationOptionValuePrefix.IsNull() && !model.CustomizationOptionValuePrefix.IsUnknown() {
		return model.CustomizationOptionValuePrefix.ValueInt64()
	}

	return deriveCustomizationOptionValuePrefix(model.CustomizationPrefix.ValueString(), model.Id.ValueString())
}

func deriveCustomizationOptionValuePrefix(prefix, publisherId string) int64 {
	if publisherId == "d21aab71-79e7-11dd-8874-00188b01e34f" {
		return 10000
	}

	normalizedPrefix := strings.ToUpper(prefix)
	return customizationOptionValuePrefixFromHash(hashCustomizationPrefix(normalizedPrefix))
}

func hashCustomizationPrefix(prefix string) int32 {
	var hash int32
	for _, ch := range prefix {
		hash = (hash << 5) - hash + ch
	}
	return hash
}

func customizationOptionValuePrefixFromHash(hash int32) int64 {
	value := int64(hash)
	if value < 0 {
		value = -value
	}
	return (value % 90000) + 10000
}

func isPublisherAlreadyExistsError(err error) bool {
	var unexpectedStatusErr customerrors.UnexpectedHttpStatusCodeError
	if !errors.As(err, &unexpectedStatusErr) {
		return false
	}

	if unexpectedStatusErr.StatusCode != http.StatusPreconditionFailed {
		return false
	}

	body := string(unexpectedStatusErr.Body)
	return strings.Contains(body, `"code":"0x80040237"`) ||
		strings.Contains(body, "matching key values already exists")
}

func nullableInt64Value(value *int64) types.Int64 {
	if value == nil {
		return types.Int64Null()
	}
	return types.Int64Value(*value)
}

func nullableFloat64Value(value *float64) types.Float64 {
	if value == nil {
		return types.Float64Null()
	}
	return types.Float64Value(*value)
}

func nullableStringPointer(value types.String) *string {
	if value.IsNull() || value.IsUnknown() {
		return nil
	}
	return value.ValueStringPointer()
}

func nullableInt64Pointer(value types.Int64) *int64 {
	if value.IsNull() || value.IsUnknown() {
		return nil
	}
	return value.ValueInt64Pointer()
}

func nullableFloat64Pointer(value types.Float64) *float64 {
	if value.IsNull() || value.IsUnknown() {
		return nil
	}
	return value.ValueFloat64Pointer()
}

func isGuid(value string) bool {
	return canonicalGuidRegex.MatchString(value)
}
