// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/microsoft/terraform-provider-power-platform/internal/powerplatform/api/bapi (interfaces: BapiClientInterface)

// Package powerplatform_mocks is a generated GoMock package.
package powerplatform_mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	powerplatform_common "github.com/microsoft/terraform-provider-power-platform/internal/powerplatform/api"
	powerplatform_models "github.com/microsoft/terraform-provider-power-platform/internal/powerplatform/models"
)

// MockBapiClientInterface is a mock of BapiClientInterface interface.
type MockBapiClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBapiClientInterfaceMockRecorder
}

// MockBapiClientInterfaceMockRecorder is the mock recorder for MockBapiClientInterface.
type MockBapiClientInterfaceMockRecorder struct {
	mock *MockBapiClientInterface
}

// NewMockBapiClientInterface creates a new mock instance.
func NewMockBapiClientInterface(ctrl *gomock.Controller) *MockBapiClientInterface {
	mock := &MockBapiClientInterface{ctrl: ctrl}
	mock.recorder = &MockBapiClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBapiClientInterface) EXPECT() *MockBapiClientInterfaceMockRecorder {
	return m.recorder
}

// CreateEnvironment mocks base method.
func (m *MockBapiClientInterface) CreateEnvironment(arg0 context.Context, arg1 powerplatform_models.EnvironmentCreateDto) (*powerplatform_models.EnvironmentDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironment", arg0, arg1)
	ret0, _ := ret[0].(*powerplatform_models.EnvironmentDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironment indicates an expected call of CreateEnvironment.
func (mr *MockBapiClientInterfaceMockRecorder) CreateEnvironment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironment", reflect.TypeOf((*MockBapiClientInterface)(nil).CreateEnvironment), arg0, arg1)
}

// CreatePolicy mocks base method.
func (m *MockBapiClientInterface) CreatePolicy(arg0 context.Context, arg1 powerplatform_models.DlpPolicyModel) (*powerplatform_models.DlpPolicyModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePolicy", arg0, arg1)
	ret0, _ := ret[0].(*powerplatform_models.DlpPolicyModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePolicy indicates an expected call of CreatePolicy.
func (mr *MockBapiClientInterfaceMockRecorder) CreatePolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePolicy", reflect.TypeOf((*MockBapiClientInterface)(nil).CreatePolicy), arg0, arg1)
}

// DeleteEnvironment mocks base method.
func (m *MockBapiClientInterface) DeleteEnvironment(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEnvironment", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEnvironment indicates an expected call of DeleteEnvironment.
func (mr *MockBapiClientInterfaceMockRecorder) DeleteEnvironment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEnvironment", reflect.TypeOf((*MockBapiClientInterface)(nil).DeleteEnvironment), arg0, arg1)
}

// DeletePolicy mocks base method.
func (m *MockBapiClientInterface) DeletePolicy(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePolicy", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePolicy indicates an expected call of DeletePolicy.
func (mr *MockBapiClientInterfaceMockRecorder) DeletePolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePolicy", reflect.TypeOf((*MockBapiClientInterface)(nil).DeletePolicy), arg0, arg1)
}

// Execute mocks base method.
func (m *MockBapiClientInterface) Execute(arg0 context.Context, arg1, arg2 string, arg3 interface{}, arg4 []int, arg5 interface{}) (*powerplatform_common.ApiHttpResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(*powerplatform_common.ApiHttpResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockBapiClientInterfaceMockRecorder) Execute(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockBapiClientInterface)(nil).Execute), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetBase mocks base method.
func (m *MockBapiClientInterface) GetBase() powerplatform_common.ApiClientInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBase")
	ret0, _ := ret[0].(powerplatform_common.ApiClientInterface)
	return ret0
}

// GetBase indicates an expected call of GetBase.
func (mr *MockBapiClientInterfaceMockRecorder) GetBase() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBase", reflect.TypeOf((*MockBapiClientInterface)(nil).GetBase))
}

// GetConnectors mocks base method.
func (m *MockBapiClientInterface) GetConnectors(arg0 context.Context) ([]powerplatform_models.ConnectorDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectors", arg0)
	ret0, _ := ret[0].([]powerplatform_models.ConnectorDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetConnectors indicates an expected call of GetConnectors.
func (mr *MockBapiClientInterfaceMockRecorder) GetConnectors(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectors", reflect.TypeOf((*MockBapiClientInterface)(nil).GetConnectors), arg0)
}

// GetEnvironment mocks base method.
func (m *MockBapiClientInterface) GetEnvironment(arg0 context.Context, arg1 string) (*powerplatform_models.EnvironmentDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironment", arg0, arg1)
	ret0, _ := ret[0].(*powerplatform_models.EnvironmentDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironment indicates an expected call of GetEnvironment.
func (mr *MockBapiClientInterfaceMockRecorder) GetEnvironment(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironment", reflect.TypeOf((*MockBapiClientInterface)(nil).GetEnvironment), arg0, arg1)
}

// GetEnvironments mocks base method.
func (m *MockBapiClientInterface) GetEnvironments(arg0 context.Context) ([]powerplatform_models.EnvironmentDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironments", arg0)
	ret0, _ := ret[0].([]powerplatform_models.EnvironmentDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironments indicates an expected call of GetEnvironments.
func (mr *MockBapiClientInterfaceMockRecorder) GetEnvironments(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironments", reflect.TypeOf((*MockBapiClientInterface)(nil).GetEnvironments), arg0)
}

// GetPolicies mocks base method.
func (m *MockBapiClientInterface) GetPolicies(arg0 context.Context) ([]powerplatform_models.DlpPolicyModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicies", arg0)
	ret0, _ := ret[0].([]powerplatform_models.DlpPolicyModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicies indicates an expected call of GetPolicies.
func (mr *MockBapiClientInterfaceMockRecorder) GetPolicies(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicies", reflect.TypeOf((*MockBapiClientInterface)(nil).GetPolicies), arg0)
}

// GetPolicy mocks base method.
func (m *MockBapiClientInterface) GetPolicy(arg0 context.Context, arg1 string) (*powerplatform_models.DlpPolicyModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPolicy", arg0, arg1)
	ret0, _ := ret[0].(*powerplatform_models.DlpPolicyModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPolicy indicates an expected call of GetPolicy.
func (mr *MockBapiClientInterfaceMockRecorder) GetPolicy(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPolicy", reflect.TypeOf((*MockBapiClientInterface)(nil).GetPolicy), arg0, arg1)
}

// GetPowerApps mocks base method.
func (m *MockBapiClientInterface) GetPowerApps(arg0 context.Context, arg1 string) ([]powerplatform_models.PowerAppBapi, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPowerApps", arg0, arg1)
	ret0, _ := ret[0].([]powerplatform_models.PowerAppBapi)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPowerApps indicates an expected call of GetPowerApps.
func (mr *MockBapiClientInterfaceMockRecorder) GetPowerApps(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPowerApps", reflect.TypeOf((*MockBapiClientInterface)(nil).GetPowerApps), arg0, arg1)
}

// UpdateEnvironment mocks base method.
func (m *MockBapiClientInterface) UpdateEnvironment(arg0 context.Context, arg1 string, arg2 powerplatform_models.EnvironmentDto) (*powerplatform_models.EnvironmentDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEnvironment", arg0, arg1, arg2)
	ret0, _ := ret[0].(*powerplatform_models.EnvironmentDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEnvironment indicates an expected call of UpdateEnvironment.
func (mr *MockBapiClientInterfaceMockRecorder) UpdateEnvironment(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEnvironment", reflect.TypeOf((*MockBapiClientInterface)(nil).UpdateEnvironment), arg0, arg1, arg2)
}

// UpdatePolicy mocks base method.
func (m *MockBapiClientInterface) UpdatePolicy(arg0 context.Context, arg1 string, arg2 powerplatform_models.DlpPolicyModel) (*powerplatform_models.DlpPolicyModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePolicy", arg0, arg1, arg2)
	ret0, _ := ret[0].(*powerplatform_models.DlpPolicyModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePolicy indicates an expected call of UpdatePolicy.
func (mr *MockBapiClientInterfaceMockRecorder) UpdatePolicy(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePolicy", reflect.TypeOf((*MockBapiClientInterface)(nil).UpdatePolicy), arg0, arg1, arg2)
}
