linters:
  enable:
    - revive
    - staticcheck
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - unused
    - godot
linters-settings:
  revive:
    enable-all-rules: true
    rules:
      - name: var-naming
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: cyclomatic
        disabled: true
  errcheck:
    # Report about not checking of errors in type assertions: `a := b.(MyStruct)`.
    # Such cases aren't reported by default.
    # Default: false
    check-type-assertions: true
  issues:
    exclude:
      - "method receiver '(d|r)' is not referenced in method's body, consider removing or renaming it as _"
      - "parameter 'ctx' seems to be unused, consider removing or renaming it as _"
      - "avoid magic numbers like '0'"
      - "string literal \"(solution_file|settings_file|CONFIGURE|PROVIDER)\" appears, at least.*"
    # exclude-rules:
    #   - linters:
    #       - revive
    #     text: "parameter 'ctx' seems to be unused, consider removing or renaming it as _"
    #   # - linters:
      #     - revive
      #   text: "avoid magic numbers like '0'"
      # - linters:
      #     - revive
      #   text: "string literal \"solution_file\" appears"


