version: "2"
linters:
  enable:
    - godot
    - revive
  settings:
    errcheck:
      check-type-assertions: true
    revive:
      enable-all-rules: true
      rules:
        - name: var-naming
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: add-constant
          disabled: true
        - name: function-length
          disabled: true
        - name: unused-parameter
          arguments:
            - allowRegex: "^(ctx|diags|req|resp)$"
        - name: cognitive-complexity
          arguments:
            - 40
          disabled: false
        - name: unused-receiver
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: receiver-naming
          disabled: true
        - name: argument-limit
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - path: (.+)\.go$
        text: ineffectual assignment to ctx
      - path: (.+)\.go$
        text: 'SA4006: this value of ctx is never used'
      - path: (.+)\.go$
        text: unused parameter (ctx|diags|req|resp)
      - path: (.+)\.go$
        text: 'exported: type name will be used as ([a-zA-Z_]+)\.([A-Za-z]+)Dto'
      - path: (.+)\.go$
        text: Error return value is not checked
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10
  max-same-issues: 10
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
