name: "Copilot Setup Steps"
description: "Install tools needed for Copilot Agent"

on: workflow_dispatch


jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: "Install Changie (changelog tool)"
        uses: miniscruff/changie-action@v2
        with:
          version: "1.21.1"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: v2.1.6

      - name: "Install Terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.4"

      - name: "Install Go tools from tools.go"
        run: |
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs@0.21.0

      - name: "Verify installation"
        run: |
          echo "=== Installed Tools Verification ==="
          changie --version
          golangci-lint --version
          terraform --version
          tfplugindocs --version
          go version
          echo "=== Setup complete ==="
