title: Terraform Provider for Power Platform
description: The Power Platform Terraform Provider allows managing environments and other resources within Power Platform.
theme: just-the-docs

url: https://microsoft.github.io/terraform-provider-power-platform/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
